### PR TITLE
configured settings to use env variables

### PR DESCRIPTION
**Pull request by seljukgulcan**

### CODE REVIEW

**Review by Gormezoglu — COMMENTED** [review]
Engine information could also be hidden in .env

**Review by ttoygar — APPROVED** [review]
ALLOWED_HOSTS, ENGINE, HOST, PORT and TIME_ZONE information could be put in .env file.

**Comment by ahmetbahadircol** [comment]
Is os library necessary for settings.py? Importing the os might be redundant.

**Comment by seljukgulcan** [comment]
ty for the reviews.

Moved some conf variables to the env file. I decided to keep ENGINE info in setting.py since PostgreSQL is a dependency of the project. I don't see a reason to hide it when it's already listed in the readme file as a prerequisite.

@ahmetbahadircol  agree, changed the file accordingly. `os.path` and `pathlib` are doing the same thing. It's better to stick with one.

**Review by Tahakbas — APPROVED** [review]

**Review by VeliAliyev — APPROVED** [review]

**Pull request closed without merging**
